Accountancy (ACCY)
Actuarial Science & Risk Management (ASRM)
Advertising (ADV)
Aerospace Engineering (AE)
African American Studies (AFRO)
African Studies (AFST)
Agr, Consumer, & Env Sciences (ACES)
Air Force Aerospace Studies (AFAS)
American Indian Studies (AIS)
Anthropology (ANTH)
Applied Health Sci Courses (AHS)
Arabic (ARAB)
Architecture (ARCH)
Art (ART)
Art--Design (ARTD)
Art--Education (ARTE)
Art--Foundation (ARTF)
Art--History (ARTH)
Art--Studio (ARTS)
Asian American Studies (AAS)
Asian Studies (ASST)
Astronomy (ASTR)
Atmospheric Sciences (ATMS)
B
Bamana (BMNA)
Basque (BASQ)
Biochemistry (BIOC)
Bioengineering (BIOE)
Biology (BIOL)
Biomedical Sciences and Engineering (BSE)
Biophysics (BIOP)
Bosnian-Croatian-Serbian (BCS)
Brain and Cognitive Science (BCOG)
Bulgarian (BULG)
Business Administration (BADM)
Business and Technical Writing (BTW)
Business (BUS)
C
Campus Honors Program (CHP)
Catalan (CATL)
Cell and Developmental Biology (CDB)
Center for Advanced Study (CAS)
Chemical and Biomolecular Engr (CHBE)
Chemistry (CHEM)
Chinese (CHIN)
Civil and Environ Engineering (CEE)
Classical Civilization (CLCV)
Clinical Sciences and Engineering (CLE)
Committee on Inst Cooperation (CIC)
Communication (CMN)
Community Health (CHLH)
Comparative Biosciences (CB)
Comparative & World Literature (CWL)
Computational Science and Engr (CSE)
Computer Science (CS)
Creative Writing (CW)

Curriculum and Instruction (CI)
Czech (CZCH)
D
Dance (DANC)
E
Earth, Society, & Environment (ESE)
E. Asian Languages & Cultures (EALC)
Economics (ECON)
Ed Policy, Org & Ldership (EPOL)
Educational Policy Studies (EPS)
Educational Practice (EDPR)
Educational Psychology (EPSY)
Education (EDUC)
Educ Organization & Leadership (EOL)
Electrical and Computer Engr (ECE)
Engineering (ENG)
Engineering Honors (ENGH)
English as an Intl Language (EIL)
English as a Second Language (ESL)
English (ENGL)
Entomology (ENT)
Environmental Studies (ENVS)
Environmental Sustainability (ENSU)
European Union Studies (EURO)
F
Finance (FIN)
Fine and Applied Arts (FAA)
Food Science & Human Nutrition (FSHN)
Foreign Language Teacher Education (FLTE)
French (FR)
G
Gender and Women's Studies (GWS)
General Engineering (GE) -- Changed to Systems Engineering and Design (SE)
General Studies (GS)
Geography (GEOG)
Geology (GEOL)
German (GER)
Germanic (GMC)
Global Studies (GLBL)
Graduate College (GC)
Grand Challenge Learning (GCL)
Greek (GRK)
H
Hebrew, Modern and Classical (HEBR)
Hindi (HNDI)
History (HIST)
Horticulture (HORT)
Human Dev and Family Studies (HDFS)
Human Dimensions of Env Sys (HDES)
Humanities Courses (HUM)
Human Resource Development (HRD)
Human Resource Education (HRE)
I
I-Health (IHLT)
Industrial Engineering (IE)
Informatics (INFO)
Information Sciences (IS)
Integrative Biology (IB)
Italian (ITAL)
J
Japanese (JAPN)
Jewish Studies (JS)
Journalism (JOUR)
K
Kinesiology (KIN)
Korean (KOR)
L
Labor and Employment Relations (LER)
Landscape Architecture (LA)
Latina/Latino Studies (LLS)
Latin American & Caribbean St (LAST)
Latin (LAT)
Law (LAW)
Liberal Arts and Sciences (LAS)
Library & Information Science (LIS) -- Changed to Information Sciences (IS)
Lingala (LGLA)
Linguistics (LING)
LiteraturesCulturesLinguistics (SLCL)
M
Materials Science & Engr (MSE)
Mathematics (MATH)
MBA Program (MBA)
Mechanical Engineering (ME)
Media and Cinema Studies (MACS)
Media (MDIA)
Medical Scholars Program (MSP)
Medieval Studies (MDVL)
Microbiology (MICR)
Military Science (MILS)
Modern Greek (GRKM)
Molecular and Cell Biology (MCB)
Moleculr & Integrative Physiol (MIP)
Museum Studies (MUSE)
Music (MUS)
N
Natural Resources & Environ Sc (NRES)
Naval Science (NS)
Neuroscience (NEUR)
Nuclear, Plasma, Radiolg Engr (NPRE)
Nutritional Sciences (NUTR)
P
Pathobiology (PATH)
Persian (PERS)
Philosophy (PHIL)
Physics (PHYS)
Plant Biology (PBIO)
Plant Pathology (PLPA)
Polish (POL)
Political Science (PS)
Portuguese (PORT)
Professional Science Master (PSM)
Psychology (PSYC)
R
Recreation, Sport, and Tourism (RST)
Rehabilitation Counseling (REHB)
Religion (REL)
Religious Studies (RLST) -- Changed to Religion (REL)
Rhetoric and Composition (RHET)
Romance Linguistics (RMLG)
Rural Sociology (RSOC)
Russian, East European and Eurasian Studies (REES)
Russian (RUSS)
S
Sanskrit (SNSK)
S. Asian & Middle Eastern (SAME)
Scandinavian (SCAN)
Second Language Studies (SLS)
Slavic (SLAV)
Social Work (SOCW)
Sociology (SOC)
Spanish (SPAN)
Special Education (SPED)
Speech and Hearing Science (SHS)
Statistics (STAT)
Strategic Brand Communication (SBC)
Swahili (SWAH)
Systems Engineering and Design (SE)
T
Technical Systems Management (TSM)
Technology and Management (TMGT)
Technology Entrepreneurship (TE)
Theatre (THEA)
Theoretical and Appl Mechanics (TAM)
Translation Studies (TRST)
Turkish (TURK)
U
Ukrainian (UKR)
Urban and Regional Planning (UP)
V
Veterinary Clinical Medicine (VCM)
Veterinary Medicine Courses (VM)
W
Wolof (WLOF)
Women and Gender in Global Perspectives (WGGP)
Writing Studies (WRIT)
Y
Yiddish (YDSH)
Z
Zulu (ZULU)
